apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-mottak
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 2Gi
      cpu: "1"
    requests:
      memory: 1Gi
      cpu: 500m
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://familie-ef-mottak.dev.intern.nav.no
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "928636f4-fd0d-4149-978e-a6fb68bb19de"  # 0000-GA-STDAPPS
  tokenx:
    enabled: true
  kafka:
    pool: nav-dev
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-soknad-api
          namespace: teamfamilie
          cluster: dev-sbs
        - application: familie-ef-soknad-api
          namespace: teamfamilie
          cluster: dev-gcp
        - application: familie-prosessering
          namespace: teamfamilie
          cluster: dev-gcp
    outbound:
      rules:
        - application: familie-ef-sak
        - application: familie-dokument
      external:
        - host: infotrygd-enslig-forsoerger.dev-fss-pub.nais.io
        - host: familie-integrasjoner.dev-fss-pub.nais.io
        - host: https://kafka-schema-registry.nais-q.adeo.no
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
  envFrom:
    - secret: familie
    - secret: familie-ef-mottak
  leaderElection: true
  gcp:
    sqlInstances:
      - type: POSTGRES_12 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        diskAutoresize: true
        tier: db-g1-small
        cascadingDelete: false
        databases:
          - name: familie-ef-mottak
            envVarPrefix: DB
