apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-mottak
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: /kv/prod/fss/familie-ef-mottak/teamfamilie
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: serviceuser/data/prod/srvfamilie-ef-mot
        mountPath: /var/run/secrets/nais.io/srvfamilie-ef-mot
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 2Gi
      cpu: "1"
    requests:
      memory: 1Gi
      cpu: 500m
  secureLogs:
    enabled: true
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://familie-ef-mottak.nais.adeo.no
    - https://familie-ef-mottak.prod-fss-pub.nais.io
    - https://familie-ef-mottak.prod-fss.nais.io
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-soknad-api
          namespace: teamfamilie
          cluster: prod-gcp
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  leaderElection: true
  envFrom:
    - configmap: loginservice-idporten
