apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-mottak
  namespace: default
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: /kv/preprod/fss/familie-ef-mottak/default
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /azuread/data/dev/creds/familie-ef-mottak
        mountPath: /var/run/secrets/nais.io/azuread
      - kvPath: /serviceuser/data/dev/srvfamilie-ef-mot
        mountPath: /var/run/secrets/nais.io/srvfamilie-ef-mot
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 4Gi
      cpu: "1"
    requests:
      memory: 2Gi
      cpu: 500m
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://familie-ef-mottak.nais.preprod.local
    - https://familie-ef-mottak.dev-fss-pub.nais.io
    - https://familie-ef-mottak.dev-fss.nais.io
  secureLogs:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: SRV_CREDENTIAL_USERNAME
      value: /run/secrets/nais.io/srvfamilie-ef-mot/username
    - name: SRV_CREDENTIAL_PASSWORD
      value: /run/secrets/nais.io/srvfamilie-ef-mot/password
  leaderElection: true

