package no.nav.familie.ef.mottak.config

const val DOKUMENTTYPE_OVERGANGSSTØNAD = "OVERGANGSSTØNAD_SØKNAD"
const val DOKUMENTTYPE_SKJEMA_ARBEIDSSØKER = "SKJEMA_ARBEIDSSØKER"
const val DOKUMENTTYPE_VEDLEGG = "OVERGANGSSTØNAD_SØKNAD_VEDLEGG"

