apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-mottak
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 2Gi
    requests:
      memory: 512Mi
      cpu: 20m
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://familie-ef-mottak.intern.dev.nav.no
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "928636f4-fd0d-4149-978e-a6fb68bb19de"  # 0000-GA-STDAPPS
  tokenx:
    enabled: true
  kafka:
    pool: nav-dev
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-soknad-api
          namespace: teamfamilie
          cluster: dev-gcp
        - application: familie-prosessering
          namespace: teamfamilie
          cluster: dev-gcp
        - application: statuspoll
          namespace: navdig
    outbound:
      rules:
        - application: familie-ef-maler
        - application: familie-brev
        - application: familie-dokument
        - application: familie-ef-sak
        - application: familie-pdf
        - application: logging
          namespace: nais-system
      external:
        - host: familie-integrasjoner.dev-fss-pub.nais.io
        - host: kafka-schema-registry.nais-q.adeo.no
        - host: teamfamilie-unleash-api.nav.cloud.nais.io
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
  envFrom:
    - secret: familie
    - secret: familie-ef-mottak
    - secret: familie-ef-mottak-unleash-api-token
  leaderElection: true
  gcp:
    sqlInstances:
      - type: POSTGRES_14 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        diskAutoresize: true
        tier: db-f1-micro
        cascadingDelete: false
        pointInTimeRecovery: false
        databases:
          - name: familie-ef-mottak
            envVarPrefix: DB
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
