apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-mottak
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 6Gi
    requests:
      memory: 1Gi
      cpu: 100m
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://familie-ef-mottak.intern.nav.no
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "87190cf3-b278-457d-8ab7-1a5c55a9edd7"  # teamfamilie
  tokenx:
    enabled: true
  kafka:
    pool: nav-prod
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-soknad-api
          namespace: teamfamilie
          cluster: prod-gcp
        - application: familie-prosessering
          namespace: teamfamilie
          cluster: prod-gcp
        - application: statuspoll
          namespace: navdig
    outbound:
      rules:
        - application: familie-ef-maler
        - application: familie-brev
        - application: familie-dokument
        - application: familie-ef-sak
        - application: familie-pdf
      external:
        - host: familie-integrasjoner.prod-fss-pub.nais.io
        - host: kafka-schema-registry.nais.adeo.no
        - host: teamfamilie-unleash-api.nav.cloud.nais.io
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  envFrom:
    - secret: familie
    - secret: familie-ef-mottak
    - secret: familie-ef-mottak-unleash-api-token
  leaderElection: true
  gcp:
    sqlInstances:
      - type: POSTGRES_14 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        diskSize: 50
        diskAutoresize: true
        tier: db-custom-1-3840
        cascadingDelete: false
        highAvailability: true
        pointInTimeRecovery: false
        maintenance:
          day: 1
          hour: 4
        databases:
          - name: familie-ef-mottak
            envVarPrefix: DB
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java

