CREATE TABLE SOKNAD (
    ID          BIGINT PRIMARY KEY,
    SOKNAD_JSON TEXT NOT NULL,
    FNR         VARCHAR(50) NOT NULL
);

CREATE SEQUENCE SOKNAD_SEQ INCREMENT BY 50 START WITH 1000000 NO CYCLE;
