package no.nav.familie.ef.mottak.no.nav.familie.ef.mottak.service

import no.nav.familie.ef.mottak.service.SøknadTreeWalker
import no.nav.familie.kontrakter.ef.søknad.*
import no.nav.familie.kontrakter.felles.objectMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import java.time.LocalDate
import java.time.Month

class SøknadTreeWalkerTest {

    @Test
    fun `finnDokumenter finner alle dokumenter i en struktur`() {

        val søknad = søknad()

        val list: List<Dokument> = SøknadTreeWalker.finnDokumenter(søknad)

        assertThat(list).contains(Dokument(Fil(byteArrayOf(12)), "giftIUtlandetDokumentasjon"),
                                  Dokument(Fil(byteArrayOf(12)), "separertEllerSkiltIUtlandetDokumentasjon"),
                                  Dokument(Fil(byteArrayOf(12)), "separasjonsbekreftelse"),
                                  Dokument(Fil(byteArrayOf(12)), "samlivsbruddsdokumentasjon"),
                                  Dokument(Fil(byteArrayOf(12)), "flyktningdokumentasjon"),
                                  Dokument(Fil(byteArrayOf(12)), "avtaleOmDeltBosted"),
                                  Dokument(Fil(byteArrayOf(12)), "samværsavtale"),
                                  Dokument(Fil(byteArrayOf(12)), "erklæringOmSamlivsbrudd"),
                                  Dokument(Fil(byteArrayOf(12)), "terminbekreftelse"),
                                  Dokument(Fil(byteArrayOf(12)), "sykdom"),
                                  Dokument(Fil(byteArrayOf(12)), "barnsSykdom"),
                                  Dokument(Fil(byteArrayOf(12)), "manglendeBarnepass"),
                                  Dokument(Fil(byteArrayOf(12)), "barnMedSærligeBehov"),
                                  Dokument(Fil(byteArrayOf(12)), "arbeidskontrakt"),
                                  Dokument(Fil(byteArrayOf(12)), "utdanningstilbud"),
                                  Dokument(Fil(byteArrayOf(12)), "oppsigelseReduksjonDokumentasjon"))
    }

    @Test
    fun `finnFelter finner alle felter i en struktur`() {

        val søknad = søknad()

        val list: Map<String, Any> = SøknadTreeWalker.mapSøknadsfelterTilMap(søknad)

        val writeValueAsString = objectMapper.writeValueAsString(list)

        @Suppress("LongLine")
        assertThat(writeValueAsString).isEqualTo("""{"label":"søknad","verdiliste":[{"label":"Personalia","verdiliste":[{"label":"fødselsnummer","verdi":"24117938529"},{"label":"navn","verdi":"hei"},{"label":"statsborgerskap","verdi":"hei"},{"label":"adresse","verdi":"Søknadsfelt(label=gatenavn, verdi=hei) Søknadsfelt(label=husnummer, verdi=1) Søknadsfelt(label=husbokstav, verdi=hei)\nSøknadsfelt(label=postnummer, verdi=hei) Søknadsfelt(label=poststedsnavn, verdi=hei)"},{"label":"telefonnummer","verdi":"hei"},{"label":"sivilstatus","verdi":"hei"}]},{"label":"Sivilstandsdetaljer","verdiliste":[{"label":"giftIUtlandet","verdi":"Ja"},{"label":"dokument","verdi":"giftIUtlandetDokumentasjon"},{"label":"separertEllerSkiltIUtlandet","verdi":"Ja"},{"label":"dokument","verdi":"separertEllerSkiltIUtlandetDokumentasjon"},{"label":"søktOmSkilsmisseSeparasjon","verdi":"Ja"},{"label":"søknadsdato","verdi":"2020-01-21"},{"label":"dokument","verdi":"separasjonsbekreftelse"},{"label":"årsakEnslig","verdi":"hei"},{"label":"dokument","verdi":"samlivsbruddsdokumentasjon"},{"label":"samlivsbruddsdato","verdi":"2020-01-21"},{"label":"fraflytningsdato","verdi":"2020-01-21"},{"label":"spesifikasjonAnnet","verdi":"hei"},{"label":"endringSamværsordningDato","verdi":"2020-01-21"}]},{"label":"Medlemskap","verdiliste":[{"label":"oppholderDuDegINorge","verdi":"Ja"},{"label":"bosattNorgeSisteÅrene","verdi":"Ja"},{"label":"flyktningstatus","verdi":"Ja"},{"label":"dokument","verdi":"flyktningdokumentasjon"}]},{"label":"Bosituasjon","verdiliste":[{"label":"delerDuBolig","verdi":"hei"},{"label":"samboerdetaljer","verdiliste":[{"label":"navn","verdi":"hei"},{"label":"fødselsdato","verdi":"2020-01-21"},{"label":"land","verdi":"hei"}]},{"label":"sammenflyttingsdato","verdi":"2020-01-21"}]},{"label":"Sivilstandsplaner","verdiliste":[{"label":"harPlaner","verdi":"Ja"},{"label":"fraDato","verdi":"2020-01-21"},{"label":"vordendeSamboerEktefelle","verdiliste":[{"label":"navn","verdi":"hei"},{"label":"fødselsdato","verdi":"2020-01-21"},{"label":"land","verdi":"hei"}]}]},{"label":"KommendeBarn","verdiliste":[{"label":"navn","verdi":"hei"},{"label":"fnr","verdi":"hei"},{"label":"annenForelder","verdiliste":[{"label":"kanIkkeOppgiAnnenForelderFar","verdi":"Ja"},{"label":"ikkeOppgittAnnenForelderBegrunnelse","verdi":"hei"},{"label":"bosattNorge","verdi":"Ja"},{"label":"personalia","verdiliste":[{"label":"navn","verdi":"hei"},{"label":"fødselsdato","verdi":"2020-01-21"},{"label":"land","verdi":"hei"}]},{"label":"adresse","verdi":"Søknadsfelt(label=gatenavn, verdi=hei) Søknadsfelt(label=husnummer, verdi=1) Søknadsfelt(label=husbokstav, verdi=hei)\nSøknadsfelt(label=postnummer, verdi=hei) Søknadsfelt(label=poststedsnavn, verdi=hei)"}]},{"label":"samvær","verdiliste":[{"label":"spørsmålAvtaleOmDeltBosted","verdi":"Ja"},{"label":"dokument","verdi":"avtaleOmDeltBosted"},{"label":"skalAnnenForelderHaSamvær","verdi":"hei"},{"label":"harDereSkriftligAvtaleOmSamvær","verdi":"hei"},{"label":"dokument","verdi":"samværsavtale"},{"label":"hvordanPraktiseresSamværet","verdi":"hei"},{"label":"borAnnenForelderISammeHus","verdi":"Ja"},{"label":"harDereTidligereBoddSammen","verdi":"Ja"},{"label":"nårFlyttetDereFraHverandre","verdi":"2020-01-21"},{"label":"dokument","verdi":"erklæringOmSamlivsbrudd"},{"label":"hvorMyeErDuSammenMedAnnenForelder","verdi":"hei"},{"label":"beskrivSamværUtenBarn","verdi":"hei"}]},{"label":"erBarnetFødt","verdi":"Ja"},{"label":"fødselTermindato","verdi":"2020-01-21"},{"label":"skalBarnetBoHosSøker","verdi":"Ja"},{"label":"dokument","verdi":"terminbekreftelse"}]},{"label":"Aktivitet","verdiliste":[{"label":"hvordanErArbeidssituasjonen","verdi":"A\nB\nC"}]},{"label":"Situasjon","verdiliste":[{"label":"gjelderDetteDeg","verdi":"A\nB\nC"},{"label":"dokument","verdi":"sykdom"},{"label":"dokument","verdi":"barnsSykdom"},{"label":"dokument","verdi":"manglendeBarnepass"},{"label":"dokument","verdi":"barnMedSærligeBehov"},{"label":"dokument","verdi":"arbeidskontrakt"},{"label":"oppstartNyJobb","verdi":"2020-01-21"},{"label":"dokument","verdi":"utdanningstilbud"},{"label":"oppstartUtdanning","verdi":"2020-01-21"},{"label":"sagtOppEllerRedusertStilling","verdi":"hei"},{"label":"oppsigelseReduksjonÅrsak","verdi":"hei"},{"label":"oppsigelseReduksjonTidspunkt","verdi":"2020-01-21"},{"label":"dokument","verdi":"oppsigelseReduksjonDokumentasjon"}]},{"label":"stønadsstart","verdiliste":[{"label":"måned","verdi":"august"},{"label":"år","verdi":"1"}]}]}""")
    }

    private fun søknad() =
            Søknad(Søknadsfelt("Søker",
                               Personalia(Søknadsfelt("Fødselsnummer", Fødselsnummer("24117938529")),
                                          Søknadsfelt("Navn", "Kari Nordmann"),
                                          Søknadsfelt("Statsborgerskap", "Norsk"),
                                          adresseSøknadsfelt(),
                                          Søknadsfelt("Telefonnummer", "12345678"),
                                          Søknadsfelt("Sivilstand", "Ugift"))),
                   Søknadsfelt("Detaljer om sivilstand",
                               Sivilstandsdetaljer(Søknadsfelt("Er du gift uten at dette er formelt registrert eller godkjent i Norge?",
                                                               true),
                                                   dokumentfelt("giftIUtlandetDokumentasjon"),
                                                   Søknadsfelt("Er du separert eller skilt uten at dette er formelt registrert eller godkjent i Norge?",
                                                               true),
                                                   dokumentfelt("separertEllerSkiltIUtlandetDokumentasjon"),
                                                   Søknadsfelt("Har dere søkt om separasjon, søkt om skilsmisse eller reist sak for domstolen?",
                                                               true),
                                                   Søknadsfelt("Når søkte dere eller reiste sak?", LocalDate.of(2015, 12, 23)),
                                                   dokumentfelt("separasjonsbekreftelse"),
                                                   Søknadsfelt("Hva er grunnen til at du er alene med barn?",
                                                               "Trives best alene"),
                                                   dokumentfelt("samlivsbruddsdokumentasjon"),
                                                   Søknadsfelt("Dato for samlivsbrudd", LocalDate.of(2014, 10, 3)),
                                                   Søknadsfelt("Når flyttet dere fra hverandre?", LocalDate.of(2014, 10, 4)),
                                                   Søknadsfelt("Hva er grunnen til at du er alene med barn?",
                                                               "Endring i samværsordning"),
                                                   Søknadsfelt("Når skjedde endringen / når skal endringen skje?",
                                                               LocalDate.of(2013, 4, 17)))),
                   Søknadsfelt("Opphold i Norge",
                               Medlemskapsdetaljer(Søknadsfelt("Oppholder du deg i Norge?", true),
                                                   Søknadsfelt("Har du bodd i Norge de siste tre årene?", true),
                                                   Søknadsfelt("",
                                                               listOf(Utenlandsopphold(Søknadsfelt("Fra",
                                                                                                   LocalDate.of(2012, 12, 4)),
                                                                                       Søknadsfelt("Til",
                                                                                                   LocalDate.of(2012, 12, 18)),
                                                                                       Søknadsfelt("Hvorfor bodde du i utlandet?",
                                                                                                   "Granca, Granca, Granca")))),
                                                   Søknadsfelt("Har du flyktningsatus hos Utlendingsdirektoratet?", true),
                                                   dokumentfelt("flyktningdokumentasjon"))),
                   Søknadsfelt("Bosituasjonen din",
                               Bosituasjon(Søknadsfelt("Deler du bolig med andre voksne?",
                                                       "Ja, jeg har samboer og lever i et ekteskapslignende forhold"),
                                           Søknadsfelt("Om samboeren din", personMinimum()),
                                           Søknadsfelt("Når flyttet dere sammen?", LocalDate.of(2018, 8, 12)))),
                   Søknadsfelt("Sivilstandsplaner",
                               Sivilstandsplaner(Søknadsfelt("Har du konkrete planer om å gifte deg eller bli samboer", true),
                                                 Søknadsfelt("Når skal dette skje?", LocalDate.of(2021, 4, 15)),
                                                 Søknadsfelt("Hvem skal du gifte deg eller bli samboer med?", personMinimum()))),
                   Søknadsfelt("Barn fra folkeregisteret",
                               listOf(Folkeregisterbarn(Søknadsfelt("Navn"),
                                                        Søknadsfelt("Fødselsnummer", Fødselsnummer("31081953069")),
                                                        Søknadsfelt("Har samme adresse som søker", true),
                                                        Søknadsfelt("Barnets andre forelder",
                                                                    Forelder(person = Søknadsfelt("personalia", personMinimum()),
                                                                             adresse = adresseSøknadsfelt())),
                                                        Søknadsfelt("samvær",
                                                                    Samvær(Søknadsfelt("Har du og den andre forelderen skriftlig avtale om delt bosted for barnet?",
                                                                                       true),
                                                                           dokumentfelt("avtaleOmDeltBosted"),
                                                                           Søknadsfelt("Har den andre forelderen samvær med barnet",
                                                                                       "Ja, men ikke mer enn vanlig samværsrett"),
                                                                           Søknadsfelt("Har dere skriftlig samværsavtale for barnet?",
                                                                                       "Ja, men den beskriver ikke når barnet er sammen med hver av foreldrene"),
                                                                           dokumentfelt("samværsavtale"),
                                                                           Søknadsfelt("Hvordan praktiserer dere samværet?",
                                                                                       "Litt hver for oss"),
                                                                           Søknadsfelt("Bor du og den andre forelderen til [barnets navn] i samme hus/blokk, gårdstun, kvartal eller vei?",
                                                                                       true),
                                                                           Søknadsfelt("Har du bodd sammen med den andre forelderen til [barnets fornavn] før?",
                                                                                       true),
                                                                           Søknadsfelt("Når flyttet dere fra hverandre?",
                                                                                       LocalDate.of(2018, 7, 21)),
                                                                           dokumentfelt("erklæringOmSamlivsbrudd"),
                                                                           Søknadsfelt("Hvor mye er du sammen med den andre forelderen til barnet?",
                                                                                       "Vi møtes også uten at barnet er til stede"),
                                                                           Søknadsfelt("Beskriv  hvor mye er du sammen med den andre forelderen til barnet?",
                                                                                       "Vi sees stadig vekk")))))),
                   Søknadsfelt("Barn lagt til",
                               listOf(KommendeBarn(navn = Søknadsfelt("Barnets fulle navn, hvis dette er bestemt"),
                                                   erBarnetFødt = Søknadsfelt("Er barnet født?"),
                                                   fødselTermindato = Søknadsfelt("Termindato"),
                                                   skalBarnetBoHosSøker = Søknadsfelt("Skal barnet bo hos deg?"),
                                                   terminbekreftelse = dokumentfelt("terminbekreftelse"),
                                                   annenForelder = Søknadsfelt("Barnets andre forelder",
                                                                               Forelder(Søknadsfelt("Jeg kan ikke oppgi den andre forelderen",
                                                                                                    true),
                                                                                        Søknadsfelt("Hvorfor kan du ikke oppgi den andre forelderen?",
                                                                                                    "Fordi jeg ikke like hen."))),
                                                   samvær = Søknadsfelt("samvær",
                                                                        Samvær(Søknadsfelt("Har du og den andre forelderen skriftlig avtale om delt bosted for barnet?",
                                                                                           true),
                                                                               dokumentfelt("avtaleOmDeltBosted"),
                                                                               Søknadsfelt("Har den andre forelderen samvær med barnet",
                                                                                           "Ja, men ikke mer enn vanlig samværsrett"),
                                                                               Søknadsfelt("Har dere skriftlig samværsavtale for barnet?",
                                                                                           "Ja, men den beskriver ikke når barnet er sammen med hver av foreldrene"),
                                                                               dokumentfelt("samværsavtale"),
                                                                               Søknadsfelt("Hvordan praktiserer dere samværet?",
                                                                                           "Litt hver for oss"),
                                                                               Søknadsfelt("Bor du og den andre forelderen til [barnets navn] i samme hus/blokk, gårdstun, kvartal eller vei?",
                                                                                           true),
                                                                               Søknadsfelt("Har du bodd sammen med den andre forelderen til [barnets fornavn] før?",
                                                                                           true),
                                                                               Søknadsfelt("Når flyttet dere fra hverandre?",
                                                                                           LocalDate.of(2018, 7, 21)),
                                                                               dokumentfelt("erklæringOmSamlivsbrudd"),
                                                                               Søknadsfelt("Hvor mye er du sammen med den andre forelderen til barnet?",
                                                                                           "Vi møtes også uten at barnet er til stede"),
                                                                               Søknadsfelt("Beskriv  hvor mye er du sammen med den andre forelderen til barnet?",
                                                                                           "Vi sees stadig vekk")))))),
                   Søknadsfelt("Arbeid, utdanning og andre aktiviteter",
                               Aktivitet(Søknadsfelt("Hvordan er arbeidssituasjonen din?",
                                                     listOf("Jeg er hjemme med barn under 1 år (vises kun hvis har barn under 1 år)",
                                                            "Jeg er i arbeid",
                                                            "Jeg er selvstendig næringsdrivende eller frilanser")),
                                         Søknadsfelt("Om arbeidsforholdet ditt",
                                                     listOf(Arbeidsgiver(Søknadsfelt("Navn på arbeidsgiveren", "Palpatine"),
                                                                         Søknadsfelt("Hvor mye jobber du?", 15),
                                                                         Søknadsfelt("Er stillingen fast eller midlertidig?",
                                                                                     "Fast"),
                                                                         Søknadfelt("Har du en sluttdato?", true),
                                                                         Søknadsfelt("Når skal du slutte?",
                                                                                     LocalDate.of(2020, 11, 18))))),
                                         Søknadsfelt("Om firmaet du driver",
                                                     Selvstendig(Selvstendig(Søknadsfelt("Navn på firma", "Bobs burgers"),
                                                                             Søknadsfelt("Organisasjonsnummer", "987654321"),
                                                                             Søknadsfelt("Når etablerte du firmaet?",
                                                                                         LocalDate.of(2018, 4, 5, )),
                                                                             Søknadsfelt("Hvor mye jobber du?", 150),
                                                                             Søknadsfelt("Hvordan ser arbeidsuken din ut?",
                                                                                         "Et evig mas")))),
                                         Søknadsfelt("Om virksomheten du etablerer",
                                                     Virksomhet(Søknadsfelt("Beskriv virksomheten",
                                                                            "Den kommer til å revolusjonere alternativ-bransjen"))),
                                         Søknadsfelt("Når du er arbeidssøker",
                                                     Arbeidssøker(Søknadsfelt("Er du registrert som arbeidssøker hos NAV?", true),
                                                                  Søknadsfelt("Er du villig til å ta imot tilbud om arbeid eller arbeidsmarkedstiltak?",
                                                                              true),
                                                                  Søknadsfelt("Kan du begynne i arbeid senest én uke etter at du har fått tilbud om jobb?",
                                                                              true),
                                                                  Søknadsfelt("Har du eller kan du skaffe barnepass senest innen en uke etter at du har fått tilbud om jobb eller arbeidsmarkedstiltak?",
                                                                              false),
                                                                  Søknadsfelt("Hvor ønsker du å søke arbeid?",
                                                                              "Kun i bodistriktet mitt, ikke mer enn 1 times reisevei"),
                                                                  Søknadsfelt("Ønsker du å stå som arbeidssøker til minst 50% stilling?",
                                                                              true))),
                                         Søknadsfelt("Utdanningen du skal ta",
                                                     UnderUtdanning(Søknadsfelt("Skole/utdanningssted", "UiO"),
                                                                    Søknadsfelt("Utdanning",
                                                                                Utdanning(Søknadsfelt("Linje/kurs/grad",
                                                                                                      "Profesjonsstudium Informatikk"),
                                                                                          Søknadsfelt("Når skal du være elev/student?",
                                                                                                      Periode(Søknadsfelt("Fra måned",
                                                                                                                          Month.JANUARY),
                                                                                                              Søknadsfelt("Fra år",
                                                                                                                          1999),
                                                                                                              Søknadsfelt("Til måned",
                                                                                                                          Month.OCTOBER),
                                                                                                              Søknadsfelt("Til år"),
                                                                                                              2004)))),
                                                                    Søknadsfelt("Er utdanningen offentlig eller privat?",
                                                                                "Offentlig"),
                                                                    Søknadsfelt("Hvor mye skal du studere?", 300),
                                                                    Søknadsfelt("Hva er målet med utdanningen?",
                                                                                "Økonomisk selvstendighet"),
                                                                    Søknadsfelt("Har du tatt utdanning etter grunnskolen?", true),
                                                                    Søknadsfelt("Tidligere Utdanning",
                                                                                listOf<>(Utdanning(Søknadsfelt("Linje/kurs/grad",
                                                                                                               "Master Fysikk"),
                                                                                                   Søknadsfelt("Når var du elev/student?",
                                                                                                               Periode(Søknadsfelt(
                                                                                                                       "Fra måned",
                                                                                                                       Month.JANUARY),
                                                                                                                       Søknadsfelt(
                                                                                                                               "Fra år",
                                                                                                                               1999),
                                                                                                                       Søknadsfelt(
                                                                                                                               "Til måned",
                                                                                                                               Month.OCTOBER),
                                                                                                                       Søknadsfelt(
                                                                                                                               "Til år"),
                                                                                                                       2004))))))))),
                   Søknadsfelt("Mer om situasjonen din",
                               Situasjon(Søknadsfelt("Gjelder noe av dette deg?",
                                                     listOf("Barnet mitt er sykt",
                                                            "Jeg har søkt om barnepass, men ikke fått plass enda",
                                                            "Jeg har barn som har behov for særlig tilsyn på grunn av fysiske, psykiske eller store sosiale problemer")),
                                         dokumentfelt("sykdom"),
                                         dokumentfelt("barnsSykdom"),
                                         dokumentfelt("manglendeBarnepass"),
                                         dokumentfelt("barnMedSærligeBehov"),
                                         dokumentfelt("arbeidskontrakt"),
                                         Søknadsfelt("Når skal du starte i ny jobb?", LocalDate.of(2045, 12, 16)),
                                         dokumentfelt("utdanningstilbud"),
                                         Søknadsfelt("Når skal du starte utdanningen?", LocalDate.of(2025, 7, 28)),
                                         Søknadsfelt("Har du sagt opp jobben eller redusert arbeidstiden de siste 6 månedene?",
                                                     true),
                                         Søknadsfelt("Hvorfor sa du opp?", "Sjefen var dum"),
                                         Søknadsfelt("Når sa du opp?", LocalDate.of(2014, 1, 12)),
                                         dokumentfelt("oppsigelseReduksjonDokumentasjon"))),
                   Søknadsfelt("Når søker du stønad fra?",
                               Stønadsstart(Søknadsfelt("Fra måned", Month.AUGUST), Søknadsfelt("Fra år", 2018))))

    private fun personMinimum(): PersonMinimum {
        return PersonMinimum(Søknadsfelt("Navn", "Bob Burger"),
                             null,
                             Søknadsfelt("Fødselsdato", LocalDate.of(1992, 2, 18)))
    }

    private fun adresseSøknadsfelt(): Søknadsfelt<Adresse> {
        return Søknadsfelt("Adresse",
                           Adresse("Jerpefaret",
                                   5,
                                   "C",
                                   "H0508",
                                   "1440",
                                   "Drøbak",
                                   "norge"))
    }

    private fun dokumentfelt(tittel: String) = Søknadsfelt("dokument", Dokument(Fil(byteArrayOf(12)), tittel))

}
